# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('vote', models.CharField(choices=[('1', 'YES'), ('0', 'MAYBE'), ('2', 'NO')], max_length=1)),
                ('question_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('1', 'BLUE'), ('2', 'RED'), ('3', 'BLACK'), ('4', 'WHITE'), ('5', 'PURPLE'), ('6', 'GREEN'), ('7', 'YELLOW'), ('8', 'BROWN'), ('9', 'GREY')], max_length=2)),
                ('_type', models.CharField(choices=[('1', 'TSHIRT'), ('2', 'SHIRT'), ('3', 'SHORT PANTS'), ('4', 'HAT'), ('5', 'SHOES'), ('6', 'HOODIE'), ('7', 'DRESS'), ('8', 'LONG PANTS'), ('9', 'SWIM SUIT'), ('10', 'SUIT')], max_length=2)),
                ('question_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateTimeField(editable=False)),
                ('score', models.IntegerField(default=10)),
                ('gender', models.CharField(choices=[('m', 'MALE'), ('f', 'FEMALE'), ('u', 'UNKOWN')], max_length=1)),
                ('num_questions', models.IntegerField(default=0)),
                ('num_answers', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dresscodeapp.Fuser')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dresscodeapp.Fuser'),
        ),
    ]
