# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dresscodeapp', '0002_auto_20170412_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 12, 13, 19, 59, 827000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='dob',
            field=models.DateTimeField(null=True, verbose_name='Date Of Birth'),
        ),
    ]
