# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dresscodeapp', '0003_auto_20170412_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 12, 17, 15, 36, 166000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date Of Birth'),
        ),
    ]
