# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dresscodeapp', '0004_auto_20170412_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 12, 18, 1, 19, 645000, tzinfo=utc), editable=False),
        ),
    ]
