# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-03 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dresscodeapp', '0008_auto_20170501_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 3, 17, 33, 9, 699000, tzinfo=utc), editable=False),
        ),
    ]
