# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-05 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dresscodeapp', '0009_auto_20170503_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 15, 50, 32, 131000, tzinfo=utc), editable=False),
        ),
    ]
