# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 20:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dresscodeapp', '0011_auto_20170513_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_system_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='type',
            field=models.CharField(choices=[('1', 'TSHIRT'), ('2', 'SHIRT'), ('3', 'SHORT PANTS'), ('4', 'HAT'), ('5', 'SHOES'), ('6', 'HOODIE'), ('7', 'DRESS'), ('9', 'SWIM SUIT'), ('10', 'SUIT'), ('11', 'PANTS'), ('12', 'SKIRT'), ('13', 'JEANS')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 20, 24, 38, 435000, tzinfo=utc), editable=False),
        ),
    ]
