# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-20 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dresscodeapp', '0014_auto_20170519_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='negative_roprts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 20, 14, 10, 4, 892000, tzinfo=utc), editable=False),
        ),
    ]
