# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-26 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dresscodeapp', '0015_auto_20170520_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='negative_roprts',
        ),
        migrations.AlterField(
            model_name='fuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 14, 11, 1, 132000, tzinfo=utc), editable=False),
        ),
    ]
