# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-26 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dresscodeapp', '0016_auto_20170526_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuser',
            name='last_ban_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 7, 19, 7, 57, 628000)),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 16, 7, 57, 628000, tzinfo=utc), editable=False),
        ),
    ]
