# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-26 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dresscodeapp', '0018_auto_20170526_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegativeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dresscodeapp.Question')),
            ],
        ),
        migrations.AlterField(
            model_name='fuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 17, 21, 51, 894000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='last_ban_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 7, 20, 21, 51, 894000)),
        ),
        migrations.AddField(
            model_name='negativereport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dresscodeapp.Fuser'),
        ),
    ]
