# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-27 20:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dresscodeapp', '0020_auto_20170526_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 27, 20, 1, 50, 353000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='last_ban_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 8, 23, 1, 50, 353000)),
        ),
    ]
