# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-28 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dresscodeapp', '0021_auto_20170527_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 16, 58, 42, 185000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='last_ban_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 19, 58, 42, 185000)),
        ),
    ]
