# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-03 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dresscodeapp', '0023_auto_20170603_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 3, 18, 4, 33, 744000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='last_ban_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 15, 21, 4, 33, 745000)),
        ),
    ]
