# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-07 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dresscodeapp', '0025_auto_20170603_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 16, 21, 29, 705000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='last_ban_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 19, 19, 21, 29, 705000)),
        ),
    ]
